<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reward extends \Application\Entity\Reward implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'isActive', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'parentId', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'points', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkMerchant', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkMerchantBranch', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkOwner');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'isActive', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'parentId', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'points', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'code', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkMerchant', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkMerchantBranch', '' . "\0" . 'Application\\Entity\\Reward' . "\0" . 'fkOwner');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reward $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentId($parentId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentId', array($parentId));

        return parent::setParentId($parentId);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentId', array());

        return parent::getParentId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoints($points)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoints', array($points));

        return parent::setPoints($points);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoints()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoints', array());

        return parent::getPoints();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkMerchant(\Application\Entity\Merchant $fkMerchant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkMerchant', array($fkMerchant));

        return parent::setFkMerchant($fkMerchant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkMerchant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkMerchant', array());

        return parent::getFkMerchant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkMerchantBranch(\Application\Entity\MerchantBranch $fkMerchantBranch = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkMerchantBranch', array($fkMerchantBranch));

        return parent::setFkMerchantBranch($fkMerchantBranch);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkMerchantBranch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkMerchantBranch', array());

        return parent::getFkMerchantBranch();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkOwner(\Application\Entity\Owner $fkOwner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkOwner', array($fkOwner));

        return parent::setFkOwner($fkOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkOwner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkOwner', array());

        return parent::getFkOwner();
    }

}
