<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Country extends \Application\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'iso', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'nicename', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'iso3', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'numcode', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'phonecode');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'name', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'iso', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'nicename', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'iso3', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'numcode', '' . "\0" . 'Application\\Entity\\Country' . "\0" . 'phonecode');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Country $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setIso($iso)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIso', array($iso));

        return parent::setIso($iso);
    }

    /**
     * {@inheritDoc}
     */
    public function getIso()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso', array());

        return parent::getIso();
    }

    /**
     * {@inheritDoc}
     */
    public function setNicename($nicename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNicename', array($nicename));

        return parent::setNicename($nicename);
    }

    /**
     * {@inheritDoc}
     */
    public function getNicename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNicename', array());

        return parent::getNicename();
    }

    /**
     * {@inheritDoc}
     */
    public function setIso3($iso3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIso3', array($iso3));

        return parent::setIso3($iso3);
    }

    /**
     * {@inheritDoc}
     */
    public function getIso3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIso3', array());

        return parent::getIso3();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumcode($numcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumcode', array($numcode));

        return parent::setNumcode($numcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumcode', array());

        return parent::getNumcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhonecode($phonecode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhonecode', array($phonecode));

        return parent::setPhonecode($phonecode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhonecode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhonecode', array());

        return parent::getPhonecode();
    }

}
