<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MerchantBranch extends \Application\Entity\MerchantBranch implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'isActive', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'longitude', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'latitude', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'phoneNumber', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'zipcode', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'permalinkPath', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'timeOffset', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'apiKey', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'eMail', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkCity', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkCountry', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkMerchant', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkState');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'id', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'isActive', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'longitude', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'latitude', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'phoneNumber', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'address', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'zipcode', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'permalinkPath', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'timeOffset', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'apiKey', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'eMail', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkCity', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkCountry', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkMerchant', '' . "\0" . 'Application\\Entity\\MerchantBranch' . "\0" . 'fkState');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (MerchantBranch $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive($isActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', array($isActive));

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsActive', array());

        return parent::getIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude($longitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', array($longitude));

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', array());

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude($latitude)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', array($latitude));

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', array());

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phoneNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phoneNumber));

        return parent::setPhoneNumber($phoneNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setZipcode($zipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZipcode', array($zipcode));

        return parent::setZipcode($zipcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZipcode', array());

        return parent::getZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPermalinkPath($permalinkPath)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPermalinkPath', array($permalinkPath));

        return parent::setPermalinkPath($permalinkPath);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermalinkPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermalinkPath', array());

        return parent::getPermalinkPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeOffset($timeOffset)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeOffset', array($timeOffset));

        return parent::setTimeOffset($timeOffset);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeOffset()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeOffset', array());

        return parent::getTimeOffset();
    }

    /**
     * {@inheritDoc}
     */
    public function setApiKey($apiKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setApiKey', array($apiKey));

        return parent::setApiKey($apiKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getApiKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApiKey', array());

        return parent::getApiKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setEMail($eMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEMail', array($eMail));

        return parent::setEMail($eMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getEMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEMail', array());

        return parent::getEMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCity(\Application\Entity\City $fkCity = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCity', array($fkCity));

        return parent::setFkCity($fkCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCity', array());

        return parent::getFkCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkCountry(\Application\Entity\Country $fkCountry = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkCountry', array($fkCountry));

        return parent::setFkCountry($fkCountry);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkCountry', array());

        return parent::getFkCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkMerchant(\Application\Entity\Merchant $fkMerchant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkMerchant', array($fkMerchant));

        return parent::setFkMerchant($fkMerchant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkMerchant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkMerchant', array());

        return parent::getFkMerchant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFkState(\Application\Entity\State $fkState = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFkState', array($fkState));

        return parent::setFkState($fkState);
    }

    /**
     * {@inheritDoc}
     */
    public function getFkState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFkState', array());

        return parent::getFkState();
    }

}
