<!-- Start Page Banner -->
<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2><?= $this->translate('Сводка') ?>
                    <small><?= $this->layout()->customer['name'] ?></small>
                </h2>
            </div>
            <div class="col-md-6">
                <ul class="breadcrumbs">
                    <li><a href="#"><?= $this->layout()->company['name'] ?></a></li>
                    <li><?= $this->translate('Сводка') ?></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Page Banner -->

<div id="content">
    <div class="container">


        <?php if (!$lastVisits && !$lastRedeems && !$merchants): ?>

            <!-- Classic Heading -->
            <h4 class="classic-title"><span><?= $this->translate('Ваша активность') ?></span></h4>

            <div class="col-md-12">
                <!-- Start Big Heading -->
                <div class="big-title text-center" style=" margin-top:25px;">
                    <h1><?= $this->translate('Всё по нулям') ?></h1>
                </div>

                <!-- Divider -->
                <div class="hr5" style=" margin-bottom:25px;"></div>

                <!-- End Big Heading -->
                <p class="text-center"
                   style="margin-bottom:20px;"><?= $this->translate('Попробуйте найти заведения где вы можете получить награду за посещения.') ?></p>

                <p class="text-center" style="margin-bottom:20px;">
                    <a href="/locations/" class="btn-system btn-large"><?= $this->translate('Найти заведения') ?></a>
                </p>
            </div>


        <?php else: ?>
            <!--Redeems-->

            <!--Visits-->

            <h4 class="classic-title"><span><?= $this->translate('Последние посещения') ?></span></h4>

            <?php if (!$lastVisits): ?>
                <div class="col-md-12">
                    <!-- Start Big Heading -->
                    <div class="big-title text-center" style=" margin-top:25px;">
                        <h1><?= $this->translate('Пусто') ?></h1>
                    </div>
                    <!-- End Big Heading -->

                    <!-- Divider -->
                    <div class="hr5" style=" margin-bottom:25px;"></div>

                    <!-- Text -->
                    <p class="text-center"
                       style="margin-bottom:20px;"><?= $this->translate('Ваши последние посещения будут отображаться в этой части страницы.') ?></p>
                </div>

            <?php else: ?>

                <div class="row  latest-posts-classic ">


                    <?php
                    /** @var \Application\Model\Entity\Visit $visit */
                    foreach ($lastVisits as $visit): ?>
                        <div class="post-row col-md-4 col-sm-4 col-xs-12">
                            <div class="left-meta-post">
                                <div class="post-date  itl-tooltip" data-placement="top"
                                     title="<?= $visit->getCreatedAt()->format('Y-m-d H:i') ?>"><span
                                        class="day"><?= $visit->getCreatedAt()->format('d') ?></span><span
                                        class="month"><?= $visit->getCreatedAt()->format('M') ?></span></div>
                                <!--<div class="post-type itl-tooltip" data-placement="bottom" title="<? /*= sprintf($this->translate('Вы получили %d баллов'), $visit->getObtainedPoints())*/ ?>"><i class="day hot">+<? /*= $visit->getObtainedPoints() */ ?></i></div>-->
                            </div>
                            <h3 class="post-title"><a
                                    href="/merchant/<?= $visit->getFkMerchantBranch()->getPermalinkPath() ?>/"><?= $visit->getFkMerchantBranch()->getFkMerchant()->getName() ?></a>
                            </h3>

                            <div class="post-content">
                                <p><?= sprintf('%s, %s %s', $visit->getFkMerchantBranch()->getAddress(), $visit->getFkMerchantBranch()->getZipcode(), $visit->getFkMerchantBranch()->getFkCity()->getName()) ?></p>
                            </div>
                        </div>
                    <?php endforeach ?>


                </div>

                <!-- Divider -->
                <div class="hr5" style="margin-top:25px;margin-bottom:45px;"></div>



            <?php endif ?>



            <h4 class="classic-title"><span><?= $this->translate('Последние награды') ?></span></h4>

            <?php if (!$lastRedeems): ?>

                <div class="col-md-12">
                    <!-- Start Big Heading -->
                    <div class="big-title text-center" style=" margin-top:25px;">
                        <h1><?= $this->translate('Пусто') ?></h1>
                    </div>
                    <!-- End Big Heading -->

                    <!-- Divider -->
                    <div class="hr5" style=" margin-bottom:25px;"></div>

                    <!-- Text -->
                    <p class="text-center"
                       style="margin-bottom:20px;"><?= $this->translate('Ваши последние награды будут отображаться в этой части страницы.') ?></p>
                </div>

            <?php else: ?>

                <div class="row  latest-posts-classic ">


                    <?php
                    /** @var \Application\Model\Entity\Redeem $redeem */
                    foreach ($lastRedeems as $redeem): ?>

                        <div class="post-row col-md-4 col-sm-4 col-xs-12">
                            <div class="left-meta-post">
                                <div class="post-date  itl-tooltip" data-placement="top"
                                     title="<?= $redeem->getCreatedAt()->format('Y-m-d') ?>"><span
                                        class="day"><?= $redeem->getCreatedAt()->format('d') ?></span><span
                                        class="month"><?= $redeem->getCreatedAt()->format('M') ?></span></div>
                                <!--<div class="post-type itl-tooltip" data-placement="bottom" title="<? /*= sprintf($this->translate('Вы потратили %d баллов'), $redeem->getFkReward()->getPoints())*/ ?>"><i class="day">-<? /*= $redeem->getFkReward()->getPoints() */ ?></i></div>-->
                            </div>
                            <h3 class="post-title"><?= $redeem->getFkReward()->getName() ?></h3>

                            <div class="post-content">
                                <p>
                                    <b><?= sprintf($this->translate('В %s'), '<a href="/merchant/' . $redeem->getFkMerchantBranch()->getPermalinkPath() . '/">' . $redeem->getFkMerchantBranch()->getFkMerchant()->getName() . '</a>') ?></b>,

                                    <?= sprintf($this->translate('за %d посещений'), $redeem->getFkReward()->getPoints()) ?>
                                    .
                                </p>
                                <!--<p><? /*= sprintf('%s, %s %s', $redeem->getFkMerchantBranch()->getAddress(), $redeem->getFkMerchantBranch()->getZipcode(), $redeem->getFkMerchantBranch()->getFkCity()->getName()) */ ?></p>-->
                            </div>
                        </div>

                    <?php endforeach ?>

                </div>

                <!-- Divider -->
                <div class="hr5" style="margin-top:25px;margin-bottom:45px;"></div>


            <?php endif ?>



            <!-- Classic Heading -->
            <h4 class="classic-title"><span><?= $this->translate('Ваши заведения') ?></span></h4>

            <?php if (!$merchants): ?>

                <div class="col-md-12">
                    <!-- Start Big Heading -->
                    <div class="big-title text-center" style=" margin-top:25px;">
                        <h1><?= $this->translate('Пусто') ?></h1>
                    </div>

                    <!-- Divider -->
                    <div class="hr5" style=" margin-bottom:25px;"></div>

                    <!-- End Big Heading -->
                    <p class="text-center"
                       style="margin-bottom:20px;"><?= $this->translate('Вы не были ни в одном из заведений где вы можно получить награду.') ?></p>

                    <p class="text-center" style="margin-bottom:20px;">
                        <a href="/locations/"
                           class="btn-system btn-large"><?= $this->translate('Найти новые заведения') ?></a>
                    </p>
                </div>

            <?php else: ?>

                <!-- Start Team Members -->
                <div class="row">

                    <?php
                    /** @var \Application\Model\Entity\MerchantsCustomers $merchant */
                    foreach ($merchants as $merchant): ?>

                        <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="team-member">
                                <!-- Memebr Photo, Name & Position -->
                                <div class="member-photo">
                                    <a href="/merchant/<?= $merchant->getFkMerchantBranch()->getPermalinkPath() ?>/">
                                        <img alt="<?= $merchant->getFkMerchant()->getName() ?>"
                                             src="/merchant/logo/<?= $merchant->getFkMerchant()->getId() ?>/"/>
                                    </a>

                                    <div class="member-name"><?= $merchant->getFkMerchant()->getName() ?>
                                        <span><?= sprintf($this->translate('%s'), $merchant->getPoints()) ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                    <?php endforeach ?>

                </div>
                <!-- End Team Members -->

            <?php endif ?>

        <?php endif ?>

    </div>
</div>
<!-- End Content -->

<?php if (!$lastVisits && !$lastRedeems && !$merchants): ?>
    <script>
        $(document).ready(function () {
            $('#elementToPointAt,#elementToPointAtForMobiles').popover({
                'placement': 'bottom',
                'content': '<?= $this->translate('Ваш уникальный QR-код! Используйте его для накопления посещений.') ?>'
            }).popover('show');
        });
    </script>
<?php endif ?>