<?= $this->partial('application/customer/partials/sub-menu.phtml', array('var'=>1)); ?>


<div id="content">
    <div class="container">


        <div class="row blog-page">

            <!--Sidebar-->
            <div class="col-md-3 sidebar left-sidebar ">
                <?= $this->partial('application/customer/partials/side-menu.phtml', array('var'=>1)); ?>
            </div>
            <!--End sidebar-->


            <!-- Start Blog Posts -->
            <div class="col-md-9 blog-box">


                <!-- Start Services Icons -->
                <div class="row">

                    <!-- Start Service Icon 1 -->
                    <div class="col-md-3 col-sm-6 service-box service-center text-center">
                        <div class="service-icon">
                            91
                        </div>
                        <div class="service-content">
                            <h4>Total visits</h4>
                        </div>
                    </div>
                    <!-- End Service Icon 1 -->

                    <!-- Start Service Icon 2 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            91
                        </div>
                        <div class="service-content">
                            <h4>Total redeems</h4>
                        </div>
                    </div>
                    <!-- End Service Icon 2 -->

                    <!-- Start Service Icon 3 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            5959
                        </div>
                        <div class="service-content">
                            <h4>Spent points</h4>
                        </div>
                    </div>
                    <!-- End Service Icon 3 -->

                    <!-- Start Service Icon 4 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            251
                        </div>
                        <div class="service-content">
                            <h4>Available points</h4>
                        </div>
                    </div>
                    <!-- End Service Icon 3 -->

                </div>
                <!-- End Services Icons -->







                <!--Redeems-->

                <h4 class="classic-title"><span>Last Redeems</span></h4>

                <div class="col-md-12">
                    <!-- Start Big Heading -->
                    <div class="big-title text-center" style=" margin-top:25px;">
                        <h1>You don't redeem</h1>
                    </div>
                    <!-- End Big Heading -->

                    <!-- Divider -->
                    <div class="hr5" style=" margin-bottom:25px;"></div>

                    <!-- Text -->
                    <p class="text-center" style="margin-bottom:20px;">Your redeems will be here</p>
                </div>

                <div class="row  latest-posts-classic ">
                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You spent 5 points"><i
                                    class="day">-5</i></div>
                        </div>
                        <h3 class="post-title"><a href="/customer/m/coca-cola/reward-program/9596/">Nice bear</a></h3>

                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>


                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You spent 5 points"><i
                                    class="day">-7</i></div>
                        </div>
                        <h3 class="post-title"><a href="/customer/m/coca-cola/reward-program/9596/">Nice cola</a></h3>

                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>


                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You spent 5 points"><i
                                    class="day">-15</i></div>
                        </div>
                        <h3 class="post-title"><a href="/user/m/coca-cola/reward-program/9596/">Something else</a></h3>

                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>

                </div>

                <!-- Divider -->
                <div class="hr5" style="margin-top:25px;margin-bottom:45px;"></div>


                <!--Visits-->

                <h4 class="classic-title"><span>Last Visits</span></h4>

                <div class="col-md-12">
                    <!-- Start Big Heading -->
                    <div class="big-title text-center" style=" margin-top:25px;">
                        <h1>You don't have any visits yet</h1>
                    </div>
                    <!-- End Big Heading -->

                    <!-- Divider -->
                    <div class="hr5" style=" margin-bottom:25px;"></div>

                    <!-- Text -->
                    <p class="text-center" style="margin-bottom:20px;">Your visits will be here</p>
                </div>

                <div class="row  latest-posts-classic ">
                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You got 5 points"><i
                                    class="day hot">+5</i></div>
                        </div>
                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>


                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You got 5 points"><i
                                    class="day hot">+7</i></div>
                        </div>
                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>


                    <div class="post-row col-md-4 col-sm-6 col-xs-12">
                        <div class="left-meta-post">
                            <div class="post-date  itl-tooltip" data-placement="top" title="Jul 29 2013"><span
                                    class="day">26</span><span class="month">Dec</span></div>
                            <div class="post-type itl-tooltip" data-placement="bottom" title="You got 5 points"><i
                                    class="day hot">+15</i></div>
                        </div>
                        <div class="post-content">
                            <p>Weteringstraat 60, 1017 SP Amsterdam</p>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>
</div>
    <!-- End Content -->