<?php

namespace Api\Model;

class Exception extends \Exception
{
    // Common
    const COMMON_INCORRECT_ARGUMENT = 1000;
    const COMMON_LOGICAL_ERROR = 1001;
    const COMMON_EMPTY_REQUEST = 1002;
    const COMMON_INTERNAL_ERROR = 1003;
    const COMMON_ROUTE_NOT_FOUND = 1004;
    const COMMON_WRONG_API_KEY = 1005;

    const QR_NOT_FOUND = 2000;
    const QR_NOT_REGISTRATED = 2001;
    const QR_COOL_DOWN = 2002;
    const QR_REGISTERED = 2003;
    const QR_EXISTS_ACTIVATED = 2004;

    const CUSTOMER_NOT_FOUND = 3000;
    const CUSTOMER_INVALID_EMAIL = 3001;
    const CUSTOMER_NOT_CONNECTED_TO_MERCHANT = 3003;
    const CUSTOMER_REWARD_NOT_FOUND = 3004;
    const CUSTOMER_NOT_POINTS = 3005;

    public static $messages = [
        self::COMMON_INCORRECT_ARGUMENT => 'COMMON_INCORRECT_ARGUMENT',
        self::COMMON_LOGICAL_ERROR => 'COMMON_LOGICAL_ERROR',
        self::COMMON_EMPTY_REQUEST => 'COMMON_EMPTY_REQUEST',
        self::COMMON_INTERNAL_ERROR => 'COMMON_INTERNAL_ERROR',
        self::COMMON_ROUTE_NOT_FOUND => 'COMMON_ROUTE_NOT_FOUND',
        self::COMMON_WRONG_API_KEY => 'COMMON_WRONG_API_KEY',

        self::QR_NOT_FOUND => 'QR_NOT_FOUND',
        self::QR_NOT_REGISTRATED => 'QR_NOT_REGISTRATED',
        self::QR_COOL_DOWN => 'QR_COOL_DOWN',
        self::QR_REGISTERED => 'QR_REGISTERED',
        self::QR_EXISTS_ACTIVATED => 'QR_EXISTS_ACTIVATED',

        self::CUSTOMER_NOT_FOUND => 'CUSTOMER_NOT_FOUND',
        self::CUSTOMER_INVALID_EMAIL => 'CUSTOMER_INVALID_EMAIL',
        self::CUSTOMER_NOT_CONNECTED_TO_MERCHANT => 'CUSTOMER_NOT_CONNECTED_TO_MERCHANT',
        self::CUSTOMER_REWARD_NOT_FOUND => 'CUSTOMER_REWARD_NOT_FOUND',
        self::CUSTOMER_NOT_POINTS => 'CUSTOMER_NOT_POINTS',
    ];
}