<div class="team-member">
    <!-- Memebr Photo, Name & Position -->
    <div class="member-photo">
        <a href="/user/m/coca-cola/">
            <img alt="" src="/images/logo/coca-cola-xxl.png"/>
        </a>

        <div class="member-name">Mandking<span>45 points</span></div>
    </div>

    <!-- Memebr Social Links -->
    <div class="member-socail  text-center" style="margin-top:20px;">
        <a class="twitter itl-tooltip" data-placement="bottom" title="twitter" href="/user/m/coca-cola/" target="_blank"><i class="fa fa-twitter"></i></a>
        <a class="yelp itl-tooltip" data-placement="bottom" title="yelp" href="#" target="_blank"><i class="fa fa-yelp"></i></a>
        <a class="facebook itl-tooltip" data-placement="bottom" title="Facebook page" href="#" target="_blank"><i class="fa fa-facebook"></i></a>
    </div>

</div>

<!-- Divider -->
<div class="hr5" style="  margin-bottom: 15px;"></div>

<!-- Categories Widget -->
<div class="widget widget-categories">
    <h4>Menu <span class="head-line"></span></h4>
    <ul>
        <li>
            <a href="/user/m/coca-cola/" class="active">Overview</a>
        </li>
        <li>
            <a href="/user/m/coca-cola/visits/">Visits</a>
        </li>
        <li>
            <a href="/user/m/coca-cola/redeems/">Redeems</a>
        </li>
    </ul>
</div>

