<!-- Start Page Banner -->
<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2>Merchant name</h2>
            </div>
            <div class="col-md-6">
                <ul class="breadcrumbs">
                    <li><a href="/"><?= $this->layout()->companyName ?></a></li>
                    <li><a href="/user/">Dashboard</a></li>
                    <li>Merchant name</li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Page Banner -->

