<!-- Start Home Page Slider -->
<section id="home">
    <!-- Carousel -->
    <div id="main-slide" class="carousel slide" >


        <!-- Carousel inner -->
        <div class="carousel-inner business-landing-bg">
            <div class="item active  ">

                <div class=" "   >
                    <div class="col-md-12 text-center business-landing"  >
                        <h1 class="animated2 business-words business-main-phrase " style="text-align: center;">
                            <?= $this->translate('Посторойте отношения с клиентами') ?>
                        </h1>

                        <h1 class="animated3 business-words business-second-phrase " style="text-align: center;">

                            <?= $this->translate('Вместе с современной цифровой системой лояльности') ?>

                        </h1>

                        <h3 class="animated3  " style="margin-top: 15px;">

                            <a style="text-transform: capitalize" href="#" onclick="window.location.hash = 'requestDemo'; return false;" data-toggle="do-not-touch" class="btn-system  border-btn btn-lg" >
                                <?= $this->layout()->company['name'] ?>
                            </a>
                        </h3>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- /carousel -->
</section>
<!-- End Home Page Slider -->


<!-- Start Services Section -->
<div class=" service">
    <div  >





        <!-- Start Full Width Section 2 -->
        <div class="section"
              >
            <div class="container">

                <div class="row  "  >

                    <!-- Start Big Heading -->
                    <div class="big-title text-center">
                        <h1><?= sprintf($this->translate('%sЦИФРОВЫЕ%s системы лояльности'), '<span class="accent-color">', '</span>') ?></h1>

                        <p class="title-desc"><?= $this->translate('Какие приимушества?') ?></p>
                    </div>
                    <!-- End Big Heading -->

                    <!-- Divider -->
                    <div class="hr5" style="margin-bottom:40px;"></div>

                    <!-- End Service Icon 4 -->

                </div>
            </div>
            <div class="container">
                <div class="row">

                    <!-- Start Service Icon 1 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-thumbs-o-up icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Клиенты ждут их') ?></h4>

                            <p><?= $this->translate('Клиенты четко смогут видеть какие награды у вас есть и что нужно чтобы получить их') ?></p>

                        </div>
                    </div>
                    <!-- End Service Icon 1 -->

                    <!-- Start Service Icon 2 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-eye icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Они интерактивны') ?></h4>

                            <p><?= $this->translate('Вы всегда сможете понять какое предложентие пользуется больше спросом') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 2 -->

                    <!-- Start Service Icon 3 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-comments-o icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Спосопствуют общению') ?></h4>

                            <p><?= $this->translate('Клиенты больше смогут узнать о вашем бизнесе, а вы о клиентах') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 3 -->

                    <!-- Start Service Icon 4 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-diamond icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Подчеркивают значимость клиента') ?></h4>

                            <p><?= $this->translate('Это способ показать на сколько клиенты важны для вас') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 4 -->
                </div>
                    <div class="row">

                    <!-- Start Service Icon 5 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-pie-chart icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Метрики') ?></h4>

                            <p><?= $this->translate('Цифры смогут показать в каком направлении двигается ваш бизнес') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 5 -->

                    <!-- Start Service Icon 6 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-download icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Автоматические данные') ?></h4>

                            <p><?= $this->translate('Все данные собираються автоматически и доступны в любой момент') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 6 -->

                    <!-- Start Service Icon 7 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-rocket icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Способ для продвижения') ?></h4>

                            <p><?= $this->translate('Ваши клинеты смогут рассказывать друзьям, какие награды были получены именно у вас') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 7 -->

                    <!-- Start Service Icon 8 -->
                    <div class="col-md-3 col-sm-6 service-box service-center">
                        <div class="service-icon">
                            <i class="fa fa-trophy icon-large"></i>
                        </div>
                        <div class="service-content">
                            <h4><?= $this->translate('Приимущество перед конкурентами') ?></h4>

                            <p><?= $this->translate('Будте на шаг впереди ваших конкурентов вместе с нами') ?></p>
                        </div>
                    </div>
                    <!-- End Service Icon 8 -->

                </div>


            </div>
        </div>
        <!-- End Full Width Section 2 -->


        <!-- Start Purchase Section -->
        <div class="section purchase business-container" style="">
            <div class="  ">

                <!-- Start Video Section Content -->
                <div class="section-video-content text-center" style="margin-bottom: 0px;">

                    <h4 class="animated2 business-words forbes">
                        <span>
                            <?= sprintf($this->translate('Сейчас тот самый момент когда использование систем лояльности через мобильные платформы стало невероятно значимо.'), '<br/>')?>

                        </span>
                    </h4>
                    <br/>
                    <h4 class="animated3 business-words forbes" >
                        <span>
                            <?= sprintf($this->translate('Если вы не используете их, ваши конкуренты будут. %sОни превратят ваших клиентов в своих фанатов.'), '<br/>')?>

                        </span>
                    </h4>

                    <div class="testimonials">
                    <div class="  forbes-testimonials">
                        <?= $this->translate('Журнал Forbes') ?>

                        <div style="display: inline-block;">
                            <a href="http://www.forbes.com/sites/ericsavitz/2012/11/28/mobile-marketing-how-to-generate-loyalty-on-the-go/" data-toggle="none"
                               target="_blank"><?= $this->translate('Ссылка на статью') ?></a>
                        </div>

                    </div>
                </div>


                </div>
                <!-- End Section Content -->

            </div>
            <!-- .container -->
        </div>


        <!-- Start Purchase Section -->
        <div class="section  ">
            <div class="container">

                <div class="row">

                    <!-- Start Left Side -->
                    <div class="col-md-8">

                        <!-- Start Big Heading -->
                        <div class="big-title">
                            <h1>
                                <strong><?= sprintf($this->translate('Почему именно %s'), '<span class="accent-color">' . $this->layout()->company['name'] . '</span>') ?></strong>
                            </h1>
                        </div>
                        <!-- End Big Heading -->



                        <!-- Divider -->
                        <div class="hr1" style="margin-bottom:14px;"></div>

                        <!-- Start Icons Lists -->
                        <div class="row">


                            <!-- Start Service Icon 1 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa fa-cogs icon-mini-effect icon-effect-3 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Полностью настраеваемая система лояльности') ?></h4>
                                </div>
                            </div>
                            <!-- End Service Icon 1 -->

                            <!-- Start Service Icon 1 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa fa-magic icon-mini-effect icon-effect-3 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Лёгкое управление и понятный интерфейс') ?></h4>
                                </div>
                            </div>
                            <!-- End Service Icon 1 -->

                            <!-- Start Service Icon 1 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa fa-desktop icon-mini-effect icon-effect-3 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Доступ с любого компьютера или телефона') ?></h4>
                                </div>
                            </div>
                            <!-- End Service Icon 1 -->

                            <!-- Start Service Icon 2 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa fa-paw icon-mini-effect icon-effect-6 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Иструмент слежения активности клиентов') ?></h4>
                                </div>
                            </div>
                            <!-- End Service Icon 2 -->

                            <!-- Start Service Icon 3 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa fa-reply icon-mini-effect icon-effect-5 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Еще одна причина клиентам возврашаться к вам') ?></h4>
                                </div>
                            </div>
                            <!-- End Service Icon 3 -->

                            <!-- Start Service Icon 4 -->
                            <div class="col-md-4 service-box service-icon-left">
                                <div class="service-icon">
                                    <i class="fa  fa-refresh icon-mini-effect icon-effect-4 gray-icon"></i>
                                </div>
                                <div class="service-content">
                                    <h4><?= $this->translate('Минимальные затраты на установку и поддержание системы') ?></h4>
                                </div>
                            </div>

                        </div>
                        <!-- End Icons Lists -->

                    </div>
                    <!-- End Left Side -->


                    <div class="col-md-4">
                        <img alt="" src="images/temp/combination.jpg" style="height: auto; width: 100%;">
                    </div>

                </div>
                <!-- End Section Content -->

            </div>
            <!-- .container -->
        </div>


        <!-- Start Purchase Section -->
        <div class="section  " id="requestDemo"
             style="padding-top:60px; padding-bottom:10px; border-top:1px solid #eee; border-bottom:1px solid #eee; background:#f9f9f9;"
           >
            <div class="container">

                <!-- Start Big Heading -->
                <div class="big-title text-center">
                    <h1><?= sprintf($this->translate('Создайте свою программу лояльности!'), $this->layout()->company['name']) ?></span></h1>

                    <p class="title-desc"><?= $this->translate('Ваши клиенты это лучшее что у вас есть.') ?></p>
                </div>
                <!-- End Big Heading -->

                <?php if (!empty($_COOKIE['requestDemo'])): ?>

                    <div class="big-title text-center">
                        <!-- Divider -->
                        <div class="hr5" style="margin-top:15px;margin-bottom:15px;"></div>
                        <p class="title-desc"><?= $this->translate('Ваш запрос успешно отправлен! Спасибо! Мы скоро свяжемся с вами.') ?></p>

                    </div>

                <?php else: ?>


                    <div id="feedbackFormSent" class="big-title text-center" style="display: none;">
                        <!-- Divider -->
                        <div class="hr5" style="margin-top:15px;margin-bottom:15px;"></div>
                        <p class="title-desc"><?= $this->translate('Ваш запрос успешно отправлен! Спасибо! Мы скоро свяжемся с вами.') ?></p>

                    </div>
                    <div id="feedbackFormProblem" class="big-title text-center" style="display: none;">
                        <!-- Divider -->
                        <div class="hr5" style="margin-top:15px;margin-bottom:15px;"></div>
                        <p class="title-desc"><?= sprintf($this->translate('К сожалению не получается отправить ваш запрос. Но вы можете позвонить нам на %s.'), '<b>' . $this->layout()->company['phone'] . '</b>') ?></p>

                    </div>


                    <div id="feedbackForm">

                        <form role="form" class="contact-form" id="contact-form" method="post" action="/ajax/feedback/">
                            <input type="hidden" name="subject" value="requestDemo">

                            <div class="row">
                                <div class="form-group col-xs-12  col-sm-6 col-md-3">
                                    <div class="controls ">
                                        <input type="text" class="phone "
                                               placeholder="<?= $this->translate('Полное имя') ?>"
                                               name="fullname">
                                    </div>
                                </div>

                                <div class="form-group col-xs-12  col-sm-6 col-md-3">
                                    <div class="controls ">
                                        <input type="text" class="phone "
                                               placeholder="<?= $this->translate('Компания') ?>"
                                               name="businessname">
                                    </div>
                                </div>

                                <div class="form-group col-xs-12  col-sm-6 col-md-3">
                                    <div class="controls ">
                                        <input type="text" class="phone " placeholder="<?= $this->translate('Email') ?>"
                                               name="email">
                                    </div>
                                </div>

                                <div class="form-group col-xs-12 col-sm-6 col-md-3">
                                    <div class="controls ">
                                        <input type="text" class="phone "
                                               placeholder="<?= $this->translate('Номер телефона') ?>"
                                               name="phonenumber">
                                    </div>
                                </div>
                            </div>

                            <div class="big-title text-center">
                                <p>
                                    <button type="submit" id="submit-feedback"
                                            class="btn-system btn-large"><?= $this->translate('Заказать обратный звонок') ?></button>
                                </p>
                                <!-- Divider -->
                                <div class="hr5" style="margin-top:30px;margin-bottom:30px;"></div>
                                <p style="font-size: 14px;">
                                    <?= sprintf($this->translate('Вопросы? Позвоните нам %s'), '<b><span class="accent-color">' . $this->layout()->company['phone'] . '</span></b>') ?>
                                </p>

                            </div>

                        </form>
                    </div>
                <?php endif ?>
            </div>
        </div>
    </div>
    <!-- .container -->
</div>
<!-- End Services Section -->


<script>

    $(document).ready(function ($) {
        $("#contact-form").submit(function (e) {
            $('#submit-feedback').prop('disable', true);
            $('#feedbackFormProblem').hide();
            var postData = $(this).serializeArray();
            var formURL = $(this).attr("action");
            $.ajax(
                {
                    url: formURL,
                    type: "POST",
                    data: postData,
                    success: function (data, textStatus, jqXHR) {
                        if (data.successUpdate) {
                            $('#submit-feedback').prop('disable', false);
                            $('#feedbackForm').hide();
                            $('#feedbackFormSent').show();
                            createCookie("requestDemo", 1, 1);
                        } else {
                            $('#feedbackFormProblem').show();
                            $('#submit-feedback').prop('disable', false);
                        }
                        $('#loader').fadeOut();
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        $('#feedbackFormProblem').show();
                        $('#submit-feedback').prop('disable', false);
                        $('#loader').fadeOut();
                    }
                });
            e.preventDefault(); //STOP default action
            //e.unbind(); //unbind. to stop multiple form submit.
            return false;
        });
    });


</script>
