<?php
/** @var \Application\Model\Entity\Reward $rewardEntity */
?>
<!-- Start Page Banner -->
<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2><?= $rewardEntity->getName()?></h2>
            </div>
            <div class="col-md-6">
                <ul class="breadcrumbs">
                    <li><a href="/"><?= $this->layout()->company['name'] ?></a></li>
                    <li><a href="/business/rewards/">Rewards</a></li>
                    <li><?= $rewardEntity->getName()?></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Page Banner -->


<div id="content">
    <div class="container">


        <div class="row">
            <div class="col-md-6">


                <h4 class="classic-title"><span><?= $this->translate('Сводка')?></span></h4>

                <!-- Start Services Icons -->
                <div class="row tex" >



                    <!-- Start Service Icon 2 -->
                    <div class="col-md-6 col-sm-6   ">

                        <div class="panel status panel-success">
                            <div class="panel-heading">
                                <h1 class="panel-title text-center"><?= $rewardEntity->getPoints()?></h1>
                            </div>
                            <div class="panel-body text-center">
                                <strong><?= $this->translate('Требуеться посещений')?></strong>
                            </div>
                        </div>
                    </div>
                    <!-- End Service Icon 2 -->

                    <!-- Start Service Icon 4 -->
                    <div class="col-md-6  col-sm-6  ">

                        <div class="panel status panel-primary">
                            <div class="panel-heading">
                                <h1 class="panel-title text-center"><?= $redeemedCount ?></h1>
                            </div>
                            <div class="panel-body text-center">
                                <strong><?= $this->translate('Использована')?></strong>
                            </div>
                        </div>

                    </div>
                    <!-- End Service Icon 3 -->



                </div>
                <!-- End Services Icons -->


                <!--Redeems-->

                <h4 class="classic-title"><span><?= $this->translate('Награждения')?></span></h4>

                <?php if (!$lastRedeems): ?>

                    <div class="col-md-12">
                        <!-- Start Big Heading -->
                        <div class="big-title text-center" style=" margin-top:25px;">
                            <h1><?= $this->translate('Награду еще ни кто не получил')?></h1>
                        </div>
                        <!-- End Big Heading -->

                        <!-- Divider -->
                        <div class="hr5" style=" margin-bottom:25px;"></div>

                        <!-- Text -->
                        <p class="text-center" style="margin-bottom:20px;"><?= $this->translate('Полученые награды ваших посетителей будут показаны тут')?></p>
                    </div>

                <?php else: ?>

                    <div class="row">
                        <div class="col-md-12">

                            <div class="table-responsive">
                                <table class="table table-reward">
                                    <thead>
                                    <tr>
                                        <th class="date-th"><?= $this->translate('Дата')?></th>
                                        <th><?= $this->translate('Клиент')?></th>
                                        <th class="text-center"><?= $this->translate('Потраченые посещения')?></th>
                                    </tr>
                                    </thead>
                                    <tbody>
                    <?php
                    /** @var \Application\Model\Entity\Redeem $redeem */
                    foreach ($lastRedeems as $redeem): ?>
                                    <tr>
                                        <td class="reward-date"><?= $redeem->getCreatedAt()->format($this->translate('d M Y в H:i')) ?></td>
                                        <td><a href="/business/client/<?= $redeem->getFkCustomer()->getId() ?>/"><?= $redeem->getFkCustomer()->getName() ?></a></td>
                                        <td class="text-center"><?= $redeem->getSpent() ?>
                                            <small class="spent-rewards"><?= sprintf($this->translate('из %s'), $redeem->getTotal())?></small>
                                        </td>
                                    </tr>
                    <?php endforeach; ?>
                                    </tbody>
                                </table>

                            </div>
                        </div>

                    </div>

                <?php endif ?>

            </div>

            <div class="col-md-6"  >

                <a class="anchor" id="change-reward"></a>

                <!--Redeems-->

                <h4 class="classic-title"><span><?= $this->translate('Изменить награду')?></span></h4>

                <?php if ($errorMessage): ?>
                    <div class="alert alert-danger">
                        <strong><?= $this->translate('Ошибка!')?></strong>
                        <br/><?= $errorMessage ?>
                    </div>
                <?php endif?>


                <?php if ($successUpdate): ?>
                    <div class="alert alert-success">
                        <strong><?= $this->translate('Отлично!')?></strong>
                        <br/><?= $this->translate('Награда обновлена!')?>
                    </div>
                <?php endif?>

                <!-- Start Contact Form -->
                <form role="form" class="contact-form verticak" id="contact-form" method="post">

                    <div class="row">
                        <div class="col-md-12">
                    <div class="form-group">
                        <div class="controls">
                            <input required="required" type="text" class="requiredField" placeholder="<?= $this->translate('Награда')?>"
                                 value="<?= $rewardEntity->getName()?>"  name="name">
                        </div>
                        </div>
                    </div>
                        <div class="col-md-3 col-xs-6">
                    <div class="form-group   ">
                        <div class="controls">
                            <input required="required" type="text" class="requiredField "
                                 value="<?= $rewardEntity->getPoints()?>"  placeholder="<?= $this->translate('Посещения')?>" name="points">
                        </div>
                        </div>
                    </div>
                    </div>
                    <!-- End Contact Form -->
                    <button type="submit" id="submit" class="btn-system btn-large"><?= $this->translate('Обновить')?></button>
                    <div id="success" style="color:#34495e;"></div>


                </form>

                <!--Redeems-->

                <h4 class="classic-title" style="  margin-top:25px;"><span><?= $this->translate('История изменений')?></span></h4>

                <?php if (!$changedHistory->count()): ?>

                    <div class="col-md-12">
                        <!-- Start Big Heading -->
                        <div class="big-title text-center" style=" margin-top:25px;">
                            <h1><?= $this->translate('Вы не меняли награду')?></h1>
                        </div>
                        <!-- End Big Heading -->

                        <!-- Divider -->
                        <div class="hr5" style=" margin-bottom:25px;"></div>

                        <!-- Text -->
                        <p class="text-center" style="margin-bottom:20px;"><?= $this->translate('Все изменения награды будут показываться тут')?></p>
                    </div>

                <?php else: ?>

                    <div class="row">
                        <div class="col-md-12">

                            <div class="table-responsive">
                                <table class="table table-reward">
                                    <thead>
                                    <tr>
                                        <th><?= $this->translate('Дата')?></th>
                                        <th><?= $this->translate('Награда')?></th>
                                        <th class="text-center"><?= $this->translate('Посещения')?></th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    <?php
                                    /** @var \Application\Model\Entity\RewardHistory $changed */
                                    foreach ($changedHistory as $changed): ?>
                                        <tr>
                                            <td class="reward-date"><?= $changed->getCreatedAt()->format($this->translate('d M Y в H:i')) ?></td>
                                            <td><?= $changed->getName() ?></td>
                                            <td class="text-center">
                                                <?= $changed->getPoints() ?>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>


                                    </tbody>
                                </table>

                            </div>
                        </div>

                    </div>

                <?php endif ?>


            </div>


        </div>

    </div>
</div>
<!-- End Content -->
