<?= $this->partial('application/common/calendar.phtml', array( )); ?>

<script src="/js/Chart.min.js"></script>
<script src="/js/Chart.StackedBar.js"></script>

<!-- Start Page Banner -->
<div class="page-banner no-subtitle">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h2><?= $this->translate('Сводка')?></h2>
            </div>
            <div class="col-md-6">
                <ul class="breadcrumbs">
                    <li><a href="/"><?= $this->layout()->company['name'] ?></a></li>
                    <li><?= $this->translate('Сводка')?></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- End Page Banner -->


<div id="content">
    <div class="container">


        <div class="row">


            <div class="col-md-6 col-xs-12 " style="margin-bottom: 25px;">


                <h4 class="classic-title"><span><?= $this->translate('Новые и Вернувшиеся клиенты')?></span></h4>

                <div class="text-center">
                    <canvas id="bar-customers"  height="250"  style="height: 250px; width: 96%;"></canvas>
                </div>


                <div class="row">

                    <div class="col-md-6 col-xs-12  col-sm-6"  >

                        <h4 class="classic-title"><span><?= $this->translate('Возраст')?></span></h4>

                        <div class="text-center">
                            <canvas id="bar-age"  height="200"  style="height: 200px; width: 96%;"></canvas>
                        </div>

                    </div>

                    <div class="col-md-6 col-xs-12 col-sm-6">

                        <h4 class="classic-title"><span><?= $this->translate('Род')?></span></h4>

                        <div class="text-center">
                            <canvas id="bar-sex"  height="200"  style="height: 200px; width: 96%;"></canvas>
                        </div>

                    </div>

                </div>


            </div>

            <div class="col-md-6 col-xs-12 ">


                <h4 class="classic-title"><span><?= $this->translate('Клиенты по дням')?></span></h4>

                <?php
                $timestamp = strtotime( '-1 month' );
                echo build_calendar(date('m', $timestamp), date('Y', $timestamp), $lastVisitors); ?>

                <?php echo build_calendar(date('m'), date('Y'), $lastVisitors); ?>

            </div>


        </div>

    </div>
</div>
<!-- End Content -->



<script>


    var data = {
        labels: [
        <?php foreach ($newAndReturned as $dates => $data): ?>
            "<?= $dates ?>",
        <?php endforeach; ?>
        ""],
        datasets: [
            {
                label: "<?= $this->translate('Новые')?>",
                fillColor: '#24CBE5',
/*                strokeColor: "rgba(151,187,205,0.8)",
                highlightFill: "rgba(151,187,205,0.75)",
                highlightStroke: "rgba(151,187,205,1)",*/
                data: [
                    <?php foreach ($newAndReturned as list($new, $returned)): ?>
                    <?= $new ?>,
                    <?php endforeach; ?>
                0]
            },
            {
                label: "<?= $this->translate('Вернувшиеся')?>",
                fillColor: '#058DC7',
                data: [
                    <?php foreach ($newAndReturned as list($new, $returned)): ?>
                    <?= $returned ?>,
                    <?php endforeach; ?>
                    0]
            }
        ]
    };
    //

    var dataPie = [
        <?php
        $i = 0;
        $colors = ['C5E5F4','9EB9E0','F7464A','46BFBD','FDB45C','48962B','FDB45C','2B4F11','53B66D','99B66D'];
        foreach ($ages as $age => $countCustomer): ?>
            {
                value: <?= $countCustomer ?>,
                color:"#<?= $colors[$i] ?>",
                label: "<?= $age /*sprintf($this->translate('%s лет'), $age)*/ ?>"
            } <?php $i++; if ($i < count($ages)): ?> , <?php endif ?>
        <?php  endforeach; ?>

    ];


    var dataSex = {
        labels: ["<?= $this->translate('Пол')?>"],
        datasets: [
            {
                label: "<?= $this->translate('Мужчины')?>",
                fillColor: '#058DC7',
              strokeColor: "rgba(220,220,220,0.8)",
                data: [<?= (isset($gender[\Application\Model\Entity\Customer::GENDER_MAN]) ? $gender[\Application\Model\Entity\Customer::GENDER_MAN] : 0) ?> ]
            },
            {
                label: "<?= $this->translate('Женщины')?>",
                fillColor: '#24CBE5',
               strokeColor: "rgba(151,187,205,0.8)",
                data: [<?= (isset($gender[\Application\Model\Entity\Customer::GENDER_WOMAN]) ? $gender[\Application\Model\Entity\Customer::GENDER_WOMAN] : 0) ?> ]
            },
            {
                label: "<?= $this->translate('Не указано')?>",
                fillColor: '#ccc',
               strokeColor: "#bbb",
                /*       highlightFill: "rgba(151,187,205,0.75)",
                highlightStroke: "rgba(151,187,205,1)",*/
                data: [<?= (isset($gender['']) ? $gender[''] : 0) ?> ]
            }
        ]
    };

    $(function() {

        Chart.defaults.global.responsive = true;
        Chart.defaults.global.animation = false;
        Chart.defaults.global.multiTooltipTemplate  = "<%if (datasetLabel){%><%=datasetLabel%>: <%}%><%= value %>"  ;


        var ctx = document.getElementById("bar-customers").getContext("2d");
        var myBarChart = new Chart(ctx).StackedBar(data, { });

        var ctxage = document.getElementById("bar-age").getContext("2d");
        var myPieChart = new Chart(ctxage).Pie(dataPie, {
            tooltipTemplate : "<%= value %> <%if (label){%><?= $this->translate('/')?> <%=label%><%}%>"
        });

        var ctxSex = document.getElementById("bar-sex").getContext("2d");
        var myBarChart = new Chart(ctxSex).Bar(dataSex, { });


    });




</script>