
<script src="https://maps.googleapis.com/maps/api/js?sensor=false&language=<?= $this->layout()->countryCode ?>"></script>
<script src="http://google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.12/src/infobox.js"></script>
<script>

    var ib = new InfoBox();

    function initialize() {

        var mapOptions = {
            zoom: 12,
            center: new google.maps.LatLng(52.363982, 4.882832),
            mapTypeId: google.maps.MapTypeId.ROADMAP,
//  styles: styles,
            scrollwheel: false
        };
        var map = new google.maps.Map(document.getElementById('map_canvas'),mapOptions);


        var infoWindow = new google.maps.InfoWindow({
            content: "loading..."

        });


        // Try HTML5 geolocation.
       /* if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function(position) {
                var pos = {
                    lat: position.coords.latitude,
                    lng: position.coords.longitude
                };

                infoWindow.setPosition(pos);
                infoWindow.setContent('Location found.');
                map.setCenter(pos);
            }, function() {
                handleLocationError(true, infoWindow, map );
            });
        } else {
            // Browser doesn't support Geolocation
            handleLocationError(false, infoWindow, map );
        }*/


        google.maps.event.addListener(map, "click", function() { ib.close() });

        setMarkers(map, sites);

    }

    function handleLocationError(browserHasGeolocation, infoWindow, map) {
        var pos = {
            lat: 52.363982,
            lng: 4.882832
        };
        infoWindow.setPosition(pos); // Ams
        infoWindow.setContent(browserHasGeolocation ?
            'Error: The Geolocation service failed.' :
            'Error: Your browser doesn\'t support geolocation.');
        map.setCenter(pos);
    }

    var sites = [
        <?php if ($merchants): ?>
            <?php
            /** @var \Application\Model\Entity\MerchantBranch $merchant */
            foreach ($merchants as $merchant): ?>
                ['<?= $merchant->getFkMerchant()->getName() ?>',
                    <?= $merchant->getLongitude() ?>,
                    <?= $merchant->getLatitude() ?>, 1, '<p class="map-bubble"><h5><?= $merchant->getFkMerchant()->getName() ?></h5><?= $merchant->getFullAddress() ?><br/><?= $merchant->getPhoneNumber() ?> <br/> <a href="/merchant/<?= $merchant->getPermalinkPath() ?>/" class="btn-system btn-medium"><?= $this->translate('Награды')?></a></p>'],
            <?php endforeach; ?>
        <?php endif ?>
    ];

    function createMarker(site, map){
        var siteLatLng = new google.maps.LatLng(site[1], site[2]);

        var pinIcon = new google.maps.MarkerImage(
            "http://www.myiconfinder.com/uploads/iconsets/64-64-a5485b563efc4511e0cd8bd04ad0fe9e.png",
            null, /* size is determined at runtime */
            null, /* origin is 0,0 */
            null /* anchor is bottom center of the scaled image */
          //  ,new google.maps.Size(42, 42)
        );

        var marker = new google.maps.Marker({
            position: siteLatLng,
            map: map,
            title: site[0],
            zIndex: site[3],
            html: site[4]
           // ,icon: pinIcon
        });
        // Begin example code to get custom infobox
        var boxText = document.createElement("div");
        boxText.style.cssText = "    background-color: #F2F2F2;        border-radius: 5px;        box-shadow: 0 0 6px #B2B2B2;        display: inline-block;        padding: 10px 18px;";
        boxText.innerHTML = marker.html;

        var myOptions = {
            content: boxText
            ,disableAutoPan: false
            ,maxWidth: 0
            ,pixelOffset: new google.maps.Size(-140, 0)
            ,zIndex: null
            ,boxStyle: {
                //background: "url('http://www2.psd100.com/ppp/2013/11/0501/Close-button-icon-1105175400.png') no-repeat"
               // ,opacity: 0.75
                 width: "280px"
            }
            //,closeBoxURL: "http://www.google.com/intl/en_us/mapfiles/close.gif"
            ,closeBoxMargin: "-10px 2px 2px 2px"
            //,closeBoxMargin: "-10px 2px 2px 2px"
            //,closeBoxURL: "http://www2.psd100.com/ppp/2013/11/0501/Close-button-icon-1105175400.png"
            ,infoBoxClearance: new google.maps.Size(1, 1)
            ,isHidden: false
            ,pane: "floatPane"
            ,enableEventPropagation: false
        };
        // end example code for custom infobox

        google.maps.event.addListener(marker, "click", function (e) {
            ib.close();
            ib.setOptions(myOptions);
            ib.open(map, this);
        });
        return marker;
    }

    function setMarkers(map, markers) {

        for (var i = 0; i < markers.length; i++) {
            createMarker(markers[i], map);
        }
    }

    google.maps.event.addDomListener(window, 'load', initialize);

    function middleInScreen(div){
        windowHeight = $(window).height();
        windowWidth = $(window).width();
        divHeight = (windowHeight - 100 - 100)/1; // heights of your header/footer
        divWidth = windowWidth / 2;
        $(div).css({/*width: divWidth+"px",*/ height: divHeight+"px"});
    }
    $(document).ready(function(){
        middleInScreen('#map_canvas')
    });

    $(window).resize(function() {
        middleInScreen('#map_canvas')
    });
</script>


<!-- Page Content -->
<div class=" " id="map_canvas"> </div>




