<div id="content" class="rules">
    <div class="container">

        <div class="row">

            <!-- Page Content -->
            <div class="col-md-12 page-content">


                <h1>Privacy Policy</h1>

                <p>Last updated: December 02, 2015</p>

                <p>This Privacy Policy governs the manner in which LekkerRewards&nbsp;collects, uses, maintains and
                    discloses
                    information collected from users (each, a "User") of the http://lekkerrewards.nl/&nbsp;website or in our application in a business place
                    ("Service"). This
                    privacy policy applies to the Service and all products and services offered by LekkerRewards.</p>
 
                <h6>Personal identification information</h6>

                

                <p>We may collect personal identification information from Users in a variety of ways, including, but
                    not limited to,
                    when Users visit our site or our application, register on the sitefill out a formsubscribe to the newsletter and in
                    connection with
                    other activities, services, features or resources we make available on our Service. Users may be asked
                    for, as
                    appropriate, name, email address, phone number, </p>

                <p>Users may, however, visit our Service anonymously.</p>

                <p>We will collect personal identification information from Users only if they voluntarily submit such
                    information to
                    us. Users can always refuse to supply personally identification information, except that it may
                    prevent them from
                    engaging in certain Service related activities.</p>

                
                <h6>Non-personal identification information</h6>

                

                <p>We may collect non-personal identification information about Users whenever they interact with our
                    Service. Non-personal
                    identification information may include the browser name, the type of computer and technical
                    information about Users
                    means of connection to our Service, such as the operating system and the Internet service providers
                    utilized and other
                    similar information.</p>

                
                <h6>Web browser cookies</h6>

                

                <p>Our Service may use "cookies" to enhance User experience. User's web browser places cookies on their
                    hard drive for
                    record-keeping purposes and sometimes to track information about them. User may choose to set their
                    web browser to
                    refuse cookies, or to alert you when cookies are being sent. If they do so, note that some parts of
                    the Service may not
                    function properly.</p>

                
                <h6>How we use collected information</h6>

                <p>LekkerRewards&nbsp;collects and uses Users personal information for the following
                    purposes:</p>
                <ul>
                    <li><i>To improve customer service</i><br>Your information helps us to more effectively respond to
                        your customer
                        service requests and support needs.
                    </li>
                    <li><i>To personalize user experience</i><br>We may use information in the aggregate to understand
                        how our Users as
                        a group use the services and resources provided on our Service.
                    </li>
                    <li><i>To improve our Service</i><br>We continually strive to improve our website offerings based on
                        the information
                        and feedback we receive from you.
                    </li>
                    <li><i>To process transactions</i><br>We may use the information Users provide about themselves. We do not share this information with outside
                        parties except to the
                        extent necessary to provide the service.
                    </li>
                    <li><i>To administer a content, promotion, survey or other Service feature</i><br>To send Users
                        information they agreed
                        to receive about topics we think will be of interest to them.
                    </li>
                    <li><em>To send periodic emails</em><br/><br/>The email address Users provide for order processing,
                        will only be
                        used to send them information and updates pertaining to their activities. It may also be used to
                        respond to their
                        inquiries, and/or other requests or questions. If User decides to opt-in to our mailing list,
                        they will receive
                        emails that may include company news, updates, related product or service information, etc. If
                        at any time the
                        User would like to unsubscribe from receiving future emails, we include detailed unsubscribe
                        instructions at the
                        bottom of each email or User may contact us via our Service.
                    </li>
                </ul>
                

                
                <h6>How we protect your information</h6>

                

                <p>We adopt appropriate data collection, storage and processing practices and security measures to
                    protect against
                    unauthorized access, alteration, disclosure or destruction of your personal information, username,
                    password,
                    transaction information and data stored on our Service.</p>

                 <h6>Sharing your personal information</h6>

                <p>We do not sell, trade, or rent Users personal
                    identification information to others. We may share generic aggregated demographic information not
                    linked to any
                    personal identification information regarding visitors and users with our business partners, trusted
                    affiliates and
                    advertisers for the purposes outlined above.We may use third party service providers to help us
                    operate our business
                    and the Service or administer activities on our behalf, such as sending out newsletters or surveys. We
                    may share your
                    information with these third parties for those limited purposes provided that you have given us your
                    permission.</p>

                 <h6>Third party websites</h6>

                <p>Users may find advertising or other content on our Service that link to the
                    sites and services of our partners, suppliers, advertisers, sponsors, licensors and other third
                    parties. We do not
                    control the content or links that appear on these sites and are not responsible for the practices
                    employed by
                    websites linked to or from our Service. In addition, these sites or services, including their content
                    and links, may be
                    constantly changing. These sites and services may have their own privacy policies and customer
                    service policies.
                    Browsing and interaction on any other website, including websites which have a link to our Service, is
                    subject to that
                    website\'s own terms and policies.</p>
                <h6>Changes to this privacy policy</h6>

                

                <p>LekkerRewards&nbsp;has the discretion to update this privacy policy at any time. When we do, revise
                    the updated date
                    at the bottom of this page,. We encourage Users to frequently check this page for any changes to
                    stay informed about
                    how we are helping to protect the personal information we collect. You acknowledge and agree that it
                    is your
                    responsibility to review this privacy policy periodically and become aware of modifications.</p>
                <h6>Your acceptance of these terms</h6>

                

                <p>By using this Service, you signify your acceptance of this policy and <a
                        href="http://lekkerrewards.nl/terms-of-use/">terms
                        of service</a>. If you do not agree to this policy, please do not use our Service. Your continued
                    use of the Service
                    following the posting of changes to this policy will be deemed your acceptance of those changes.</p>


                <h6>Contacting us</h6>

                

                <p>If you have any questions about this Privacy Policy, the practices of this site, or your dealings
                    with this site,
                    please contact us at:</p>
                <p>
                    LekkerRewards<br/>http://lekkerrewards.nl/<br/>
                    Overschiestraat 2A3, 1062XE,
                    Amsterdam<br/>+31 6 83899381<br/>
                    support@lekkerrewards.nl
                </p>

            </div>
        </div>
    </div>
</div>